watch:
  - path: "/home/alyson/Applications/Obsidian/Life/Journal"
    recursive: true
  - path: "/home/alyson/Applications/Obsidian/Life/Notes"
    recursive: false
suffixes:
  - ".md"
  - ".txt"
ts_format: "FULL"  # SHORT or FULL
stats_separator: "\n---"